repos:
  - repo: local
    hooks:
      - id: trufflehog-scan
        name: TruffleHog Secret Scan
        description: Detect hardcoded secrets before commit
        entry: bash -c 'trufflehog git file://. --since-commit HEAD~1 --only-verified --no-update'
        language: system
        pass_filenames: false
        stages: [commit]
