name: Terraform CI - ApexVirtual Prod

on:
  push:
    branches:
      - main
    paths:
      - 'live/apexvirtual/prod/**'
      - 'modules/**'
      - '.tflint.hcl'
      - '.github/workflows/terraform-apexvirtual-prod.yaml'
  pull_request:
    branches:
      - main
    paths:
      - 'live/apexvirtual/prod/**'
      - 'modules/**'
      - '.tflint.hcl'
      - '.github/workflows/terraform-apexvirtual-prod.yaml'

permissions:
  id-token: write
  contents: read

jobs:
  validate-and-plan:
    environment: av-azure-prod
    env:
      VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      ARM_BACKEND_CONTAINER: ${{ secrets.ARM_BACKEND_CONTAINER }}
      ARM_BACKEND_KEY: ${{ secrets.ARM_BACKEND_KEY }}
      ARM_USE_OIDC: true
    runs-on: arc-runner-set
    defaults:
      run:
        shell: bash
        working-directory: ./live/av-azure/prod
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Clear TruffleHog Image Cache
      run: |
        docker rmi ghcr.io/trufflesecurity/trufflehog:3.90.6 || true
        docker rmi ghcr.io/trufflesecurity/trufflehog:latest || true

    - name: Run TruffleHog Secrets Scan
      uses: trufflesecurity/trufflehog@v3.90.6
      with:
        path: .
        extra_args: --only-verified
      continue-on-error: false

    - name: Install TFLint
      run: |
        curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
        tflint --version

    - name: Run TFLint
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        tflint --init --config=${{ github.workspace }}/.tflint.hcl
        tflint --config=${{ github.workspace }}/.tflint.hcl

    - name: Import Secrets from HashiCorp Vault
      uses: hashicorp/vault-action@v3
      with:
        url: ${{ secrets.VAULT_ADDR }}
        role: apexvirtual-terraform-role
        method: jwt
        jwtGithubAudience: ${{ secrets.VAULT_ADDR }}
        secrets: |
          kv/data/apexvirtual-prod/azure-credentials ARM_CLIENT_ID | ARM_CLIENT_ID;
          kv/data/apexvirtual-prod/azure-credentials ARM_TENANT_ID | ARM_TENANT_ID;
          kv/data/apexvirtual-prod/azure-credentials ARM_SUBSCRIPTION_ID | ARM_SUBSCRIPTION_ID;
          kv/data/apexvirtual-prod/azure-credentials db_admin_password | TF_VAR_db_admin_password;
          kv/data/apexvirtual-prod/azure-credentials db_admin_login | TF_VAR_db_admin_login;
          kv/data/apexvirtual-prod/azure-credentials admin_username | TF_VAR_admin_username;
          kv/data/apexvirtual-prod/ssh-keys user_public_key | TF_VAR_user_public_key;
          kv/data/apexvirtual-prod/azure-config network_rules_ip_rules | TF_VAR_network_rules_ip_rules
        exportEnv: true
        exportToken: true
        outputToken: false
        tlsSkipVerify: false
        jwtTtl: 3600
        ignoreNotFound: false

    - name: Install Azure CLI
      run: |
        echo "Installing Azure CLI..."
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        az --version

    - name: Azure Login using OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ env.ARM_CLIENT_ID }}
        tenant-id: ${{ env.ARM_TENANT_ID }}
        subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}

    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: '22.16.0'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.13.1

    - name: Terraform Init
      env:
        VAULT_TOKEN: ${{ env.VAULT_TOKEN }}
      run: |
        terraform init -no-color \
          -backend-config="resource_group_name=${{ secrets.ARM_BACKEND_RG }}" \
          -backend-config="storage_account_name=${{ secrets.ARM_BACKEND_STORAGE_ACCOUNT }}" \
          -backend-config="container_name=${{ env.ARM_BACKEND_CONTAINER }}" \
          -backend-config="key=${{ env.ARM_BACKEND_KEY }}"

    - name: Terraform Format Check
      run: terraform fmt -check -no-color

    - name: Terraform Validate
      run: terraform validate -no-color

    - name: Terraform Plan
      run: terraform plan -no-color -out=tfplan -var-file="prod.tfvars"